{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    {{- include "trivy-operator-polr-adapter.labels" . | nindent 4 }}
  name: {{ include "trivy-operator-polr-adapter.fullname" . }}
rules:
- apiGroups:
  - 'aquasecurity.github.io'
  resources:
  - vulnerabilityreports
  - configauditreports
  - ciskubebenchreports
  - clustercompliancereports
  - rbacassessmentreports
  - clusterrbacassessmentreports
  - exposedsecretreports
  - infraassessmentreports
  - clusterinfraassessmentreports
  - clustervulnerabilityreports
  verbs:
  - get
  - list
  - watch
{{- if .Values.openreports.enabled }}
- apiGroups:
  - 'openreports.io'
  resources:
  - reports
  - reports/status
  - clusterreports
  - clusterreports/status
  verbs:
  - get
  - create
  - update
  - delete
{{- else }}
- apiGroups:
  - 'wgpolicyk8s.io'
  resources:
  - policyreports
  - policyreports/status
  - clusterpolicyreports
  - clusterpolicyreports/status
  verbs:
  - get
  - create
  - update
  - delete
{{- end }}
- apiGroups:
  - 'apiextensions.k8s.io'
  resources:
  - customresourcedefinitions
  verbs:
  - get
{{- end -}}
