name: Lint helm chart

on:
  push:
    # run pipeline on push on master
    branches:
      - main
      - development
    paths:
      - "charts/**"
  
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: "0"

      - name: chart-testing (ct lint)
        uses: helm/chart-testing-action@v2.7.0

      - name: Run Helm Chart lint
        run: |
            ct lint --lint-conf=.github/ct_lintconf.yaml \
                    --chart-yaml-schema=.github/ct_chart_schema.yaml \
                    --target-branch=main --validate-maintainers=false \
                    --chart-dirs charts
